### PR TITLE
fix: carousel dots missing

### LINKED ISSUE #184: [bug]: Carousel dots have gone missing
## 🐛 Bug Report
The dots that sit underneath a media block to indicate how many assets are within a carousel, is no longer there. The padding between the assets indicates that its still there but is maybe hidden. This is for both desktop and mobile. Image captions are still visible.

Screenshot 2022-05-18 at 17 11 32

## To Reproduce
I first noticed the problem for the carousel on DO Lectures case study. You can also upload multiple assets into one media block in order to replicate this.

## Expected behavior
The small dots should sit on the far right hand side of the media block for all blocks that have more than one asset uploaded to it. This should be for both desktop and mobile.

## Environment

| Info             | Version(s) |
| ---------------- | ---------- |
| Browser          |       Chrome     |
| Device           |   Desktop       |
| Operating System |     MacOS Monterey       |

### PR DESCRIPTION
**Pull request by elenamarinaki**
### Why

Resolves #184 

### What

- changed the variable that was passed into the `backgroundColor` with the updated `blue100` from the `stitches` configuration file
- so that I can always keep the 3 dots on the right side of the carousel and not moving, I always have the `CaptionText` rendering even when it has no text inside. This keeps the layout consistent.

### Checklist

- [ ] Ready to be merged

### CODE REVIEW

File: packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx [hunk 1]
```diff
@@ -252,7 +254,7 @@ const Dot = styled('div', {
   width: 6,
   height: 6,
   borderRadius: '$circle',
-  backgroundColor: '$darkBlue',
+  backgroundColor: '$blue100',
```
Comment (joshuaellis) [inline packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx:257]: In the designs this is a shade of black not blue

File: packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx [hunk 2]
```diff
@@ -177,7 +177,9 @@ export const Carousel = (props: Sanity.BlockMedia) => {
         <Caption>
           {items[activeIndex].caption ? (
             <CaptionText>{items[activeIndex].caption}</CaptionText>
-          ) : null}
+          ) : (
```
Comment (joshuaellis) [inline packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx:180]: this can probably be inlined no? we're still rendering the element regardless.

**Review by joshuaellis — CHANGES_REQUESTED** [review]

File: packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx (hunk 2 above)
Comment (elenamarinaki) [reply packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx:180]: @joshuaellis 

`inlined` meaning where? I thought the `CaptionText` renders only when we have a caption. If not we have no first item in the flex and the 3 dots are taking its place and moving to the left.

Comment (joshuaellis) [reply packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx:180]: I mean couldn't we remove the ternary and just render the component always, if there's no caption, there's no caption no text will render.

Comment (elenamarinaki) [reply packages/web/src/client/components/Blocks/BlocksCarousel/index.tsx:180]: oh yes, sorry, got stack on the `inline` part

**Review by joshuaellis — APPROVED** [review]
