### PR TITLE
fix: larger max width for desktop up

### LINKED ISSUE #216: Width of paragraph on desktop
[](https://mrkr.io/s/628aa48f416b11207ab7ecb4/0)

Steps to reproduce:

Visit DO page

Actual result:

The current max-width is something around the 650px mark, but when the type is bigger, this is too tight.

Expected result:

Can we please increase this to 800x?

---

**Source URL:** [https://companion-studio-eta.vercel.app/projects/do-lectures](https://companion-studio-eta.vercel.app/projects/do-lectures)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628aa48f416b11207ab7ecb7_caddb9372c1dc37b)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

### PR DESCRIPTION
**Pull request by elenamarinaki**
in testimonial blocks

### Why

Resolves #216 

### What

added new breakpoint for `desktopUp`

### Checklist

- [ ] Ready to be merged

### CODE REVIEW

File: packages/web/src/client/components/Blocks/BlockTestimonial.tsx [hunk 1]
```diff
@@ -41,6 +41,9 @@ const TestimonialWrapper = styled(FadeIn, {
   '@tabletUp': {
     maxWidth: '$centeredParagraph',
   },
+  '@desktopUp': {
+    maxWidth: '800px',
```
Comment (joshuaellis) [inline packages/web/src/client/components/Blocks/BlockTestimonial.tsx:45]: Is there a reason that a. You didn't use the theme token & b. Only applied this on Desktop, not changing the tablet setting below?

**Review by joshuaellis — CHANGES_REQUESTED** [review]

File: packages/web/src/client/components/Blocks/BlockTestimonial.tsx (hunk 1 above)
Comment (elenamarinaki) [reply packages/web/src/client/components/Blocks/BlockTestimonial.tsx:45]: @joshuaellis on tablet it looked so wide with barely any space left on the sides. Also, Myles mentioned specifically the desktop in the ticket, so these both combined made me thing it might be a better idea to apply it there.
The `centeredParagraph` has one specific value 65.3rem and we want 800px specifically.

Comment (elenamarinaki) [reply packages/web/src/client/components/Blocks/BlockTestimonial.tsx]: ah, didn't realise the `documentWrapper` was the same size, cool :)

**Review by joshuaellis — APPROVED** [review]

**Review by mylespalmer — APPROVED** [review]

**Review by joshuaellis — APPROVED** [review]
